---
collections:
  - name: amazon.aws
    version: 10.1.2
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.controller
    version: 4.7.4
  - name: ansible.platform
    version: 2.6.20250924
  - name: infra.aap_configuration
    version: 3.8.3
  - name: community.general
    version: 12.0.1
  - name: redhat.rhel_system_roles
    version: 1.108.6
  - name: redhat.insights
    version: 1.3.0
  - name: redhat.satellite
    version: 5.7.0
  - name: ansible.hub
    version: 1.0.2
  - name: ansible.eda
    version: 2.10.0
