---
- name: Creating local accounts, distributing public keys, setting up sudoers access
  tags:
    - create
  block:

    - name: Include our user info
      ansible.builtin.include_vars:
        file: files/{{ account_create_user_list_vault }}

    - name: Grab vault from remote url
      delegate_to: localhost
      become: false
      ansible.builtin.get_url:
        url: '{{ my_remote_vault }}'
        dest: files/remotevault.yml
        mode: '0644'

    - name: Include our vault info
      delegate_to: localhost
      become: false
      ansible.builtin.include_vars:
        file: files/remotevault.yml

    - name: Ensure users are created
      loop: "{{ users }}"
      no_log: false
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        password: "{{ item['user_password'] | password_hash('sha512') }}"
        update_password: on_create
        comment: "{{ item['user_comment'] }}"
        home: "{{ item['user_home'] }}"

    - name: Create sudoers in sudoers.d directory
      loop: "{{ users }}"
      when: item['sudoers_account'] is true
      no_log: true
      ansible.builtin.copy:
        dest: /etc/sudoers.d/{{ item['name'] }}
        content: "{{ item['name'] }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: ug+rwX,o=

    - name: Making sure the public keys are in place
      loop: "{{ keys }}"
      ansible.posix.authorized_key:
        user: "{{ item['name'] }}"
        state: present
        key: "{{ lookup('file', item['key']) }}"
