---
- name: Linux post install aka configuration management
  tags:
    - create
  block:

    - name: Install Chrony
      ansible.builtin.dnf:
        name: chrony
        state: installed

    - name: Enable Chrony
      ansible.builtin.systemd_service:
        name: chronyd
        state: started
        enabled: true

    - name: Making sure cockpit in not installed
      ansible.builtin.dnf:
        name:
          - cockpit
        state: absent

    - name: Patching my_packages
      register: dnf_patch
      ansible.builtin.dnf:
        name: '*'
        skip_broken: true
        update_only: true
        state: latest

    - name: Run the insights-client to update insights vulnerability data
      register: result
      changed_when: result.rc == 1
      failed_when: result.rc > 1
      ansible.builtin.command:
        cmd: insights-client

    - name: Update the /etc/hosts file
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
        backup: true

    - name: Copy the sshd-banner file into place
      ansible.builtin.copy:
        src: files/sshd-banner
        dest: /etc/ssh/sshd-banner
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Updating the sshd_config file to show the new banner
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: ^#Banner none
        line: Banner /etc/ssh/sshd-banner

    - name: Reloading sshd service
      ansible.builtin.systemd:
        state: reloaded
        name: sshd.service
        enabled: true

    - name: Copy the new /etc/motd into place
      ansible.builtin.copy:
        src: files/motd
        dest: /etc/motd
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Copy the new /etc/issue into place
      ansible.builtin.copy:
        src: files/issue
        dest: /etc/issue
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Make sure the /etc/motd.d directory exists
      ansible.builtin.file:
        path: /etc/motd.d
        state: directory
        mode: "0755"

    - name: Make sure the /etc/cockpit directory exists
      ansible.builtin.file:
        path: /etc/cockpit
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy the /etc/issue.cockpit into place
      ansible.builtin.copy:
        src: files/issue.cockpit
        dest: /etc/issue.cockpit
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Copy the /etc/cockpit/cockpit.conf into place
      ansible.builtin.copy:
        src: files/cockpit.conf
        dest: /etc/cockpit/cockpit.conf
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Check to see if we need a reboot
      register: reboot_required
      ansible.builtin.stat:
        path: /var/run/reboot-required

    - name: Reboot the machine if it is required
      when: reboot_required.stat.exists
      ansible.builtin.reboot:
